### ISSUE TITLE
why not use psutils

### ISSUE THREAD

**Issue by lesmana** [walles/px#26]
i wonder why you chose to parse `ps` instead of using psutil.
https://github.com/giampaolo/psutil

i found this commit where you removed psutil
https://github.com/walles/px/commit/da9b56b949ab7d5a96dd57c1ee28feb65fdb75bd

i think parsing `ps` is cumbersome and error prone. the output is not meant to be parsed. it is meant, ironically, for humans. also the options and output differ from system to system. the word on the street is that, when you need to know things about processes programatically, you should parse `/proc`. or use a lib like psutil. which already does the dirty work for you.
https://stackoverflow.com/questions/2703640/process-list-on-linux-via-python

can you elaborate why you chose to not use psutil? do the arguments still hold today?

**Comment by walles** [comment]
`psutil` has binary dependencies.

Thus, using `psutil` would require me to release separate binaries for Linux and OS X, rather than one `px.pex` which works on both systems.

Also, on OS X, you must be `root` to get at certain process information (don't remember which one any more). To get at that, `psutil` would need to launch `ps` anyway (which is setuid root on OS X), or one would have to be `root` to be able to run `px`, which would be bad.

It's some combination of the above reasons.

As you noted, the corresponding commit comment wasn't very helpful, sorry about that.

IME `ps` output is actually the same between Linux and OS X, so parsing `ps` output isn't that bad. `/proc` doesn't exist on OS X, and I prefer having one list-processes implementation rather than multiple.

Does this answer your questions?

**Comment by lesmana** [comment]
thank you. that answers my question. i understand the complications.

i did not know that osx has no `/proc`. i only use linux.
